# Generated by Django 5.0.6 on 2024-06-28 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("brandenburg_plants", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="solarplant",
            name="name",
        ),
    ]
